### ISSUE TITLE
ReferenceError: React is not defined

### ISSUE THREAD

**Issue by rrobles9112** [jcmcneal/react-step-wizard#1]
hello your component and give the follow problems 
My react js version is create-react-app version 0.6.0 with react js and react dom 15.6.1

![error](https://user-images.githubusercontent.com/2179333/29481080-36e1f8b6-8443-11e7-82ec-4dbdd4efe031.png)

What could be the solution to this problem?

any help please

**Comment by jcmcneal** [comment]
This component doesn't include React internally. If you load React into your app externally as a script tag that may fix the error. I may update it to include React internally.

**Comment by jcmcneal** [comment]
I've updated it to include React internally and not rely on external react/react-dom scripts
