### ISSUE TITLE
Crash when single child present

### ISSUE THREAD

**Issue by jorbascrumps** [jcmcneal/react-step-wizard#12]
The following error occurs when there is only a single child passed to `StepWizard`:

> Uncaught TypeError: o.props.children.forEach is not a function

You may want to consider guarding against this at least for developer sanity :)

**Comment by jcmcneal** [comment]
Good catch, I'll work on fixing this one. Sorry if this drove you mad!

**Comment by Pautomagi** [comment]
Sorry to bring this one up again. Almost lost my sanity. This seems to be a bug still in 5.3.2.

Can be replicated like this.
This is not a major issue IMO as most wizard will contain multiple steps. But it threw me off when starting the development and only having the first step.

```
import React from "react";
import StepWizard from "react-step-wizard";

const App = () => {
  return (
    <div>
      <StepWizard>
        <Step1 />
      </StepWizard>
    </div>
  );
};
export default App;

const Step1 = props => {
  return (
    <div>
      <h1>Step1</h1>
    </div>
  );
};
```
