### ISSUE TITLE
Unrecognized prop warning when inlining children

### ISSUE THREAD

**Issue by jorbascrumps** [jcmcneal/react-step-wizard#13]
The following series of warnings are generated when children are inlined instead of abstracted into their own components:

>VM10074:794 Warning: React does not recognize the `totalSteps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `totalsteps` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

Repro test case:
```js
const Wizard = () =>
    <StepWizard>
        <div>1</div>
        <div>2</div>
    </StepWizard>;
```
Admittedly not best practice but there are use cases for structuring an app this way (small prototype, for example).

**Comment by jcmcneal** [comment]
Thanks for brining these issues up as it helps makes this library more stable. React throws an error when trying to pass props to a DOM element so either I don't pass the available props to the element or wrap them in a component for you. What are your thoughts?

**Comment by mathvaleriano** [comment]
I just passed my components to steps and adapt the props to styled components. 
For example (you cannot pass bool values to tags html like this) :

```
const StyledContainer = styled.div`
  background: ${({active}) => active ? '#000' : '#fff'}
`
const Foo = ({ isActive }) => (
  <StyledContainer active={isActive ? 1 : 0}>BAR</StyledContainer>
)

const Wizard = ({ initialStep, isHashEnabled, isLazyMount }) => (
  <StepWizard
        nav={<Nav />}
        initialStep={initialStep}
        isHashEnabled={isHashEnabled}
        isLazyMount={isLazyMount}
      >
      <Foo />
      { /* other components here */}
  </SetpWizard>
)
```

**Comment by jorbascrumps** [comment]
You could try checking if the child is a valid React component before passing props. Using something like `child.prototype.isReactComponent` and, if needed, `typeof child === 'function'`?
