### ISSUE TITLE
custom transition issue

### ISSUE THREAD

**Issue by anitta-paul** [jcmcneal/react-step-wizard#15]
HI,
I am using custom transition animation for my wizard steps. For me the `enterLeft` and `enterRight` transitions are working fine. But the other two, `exitLeft` and `exitRight` animations are not working.

I hope the exit animations are applied to the one step when the other step comes in.

**Comment by jcmcneal** [comment]
The exit animations should be applied to the step that you are navigating away from. I will look and see if there's a bug in the code and get back to you.

**Comment by smeevil** [comment]
I encountered the same problem, but also with the default transitions. You can also see it in the gif in the readme. when you navigate to left or right, you exit transition just blanks out.

**Comment by lindalevanen** [comment]
This is because the Step's display is set to none at the exact moment the transition begins. The problem is fixed if you don't hide the previous step at all which doesn't seem to be necessary, and set the Step's position to absolute, so they won't interfer each other.

Would love to use this library, could this be fixed?

**Comment by jcmcneal** [comment]
I'll see if I can put in a fix for it this weekend.

**Comment by jcmcneal** [comment]
Ok I fixed the exit transitions in [v5.1.0](https://github.com/jcmcneal/react-step-wizard/releases/tag/5.1.0).

Thanks for all your input and motivating me to fix this 🙌🏼

Let me know if you run into any issues with it.

**Comment by smeevil** [comment]
Works as a charm! Thank you for taking the time to fix this :)
