### ISSUE TITLE
Please remove min-height from step-wizard

### ISSUE THREAD

**Issue by mathvaleriano** [jcmcneal/react-step-wizard#17]
Could you remove the min-height attribute from step-wizard? It's breaking my layout.

**Comment by jcmcneal** [comment]
Yeah I can remove that. It was leftover code from old versions.

**Comment by mathvaleriano** [comment]
thanks .... this lib is awesome.. i wanna find time to contribute with something. Are you accepting PRs?

**Comment by jcmcneal** [comment]
I'm open to PRs so long as they are thoroughly thought out and tested in all browsers, back to IE 11. I need to put a contributing guide to the readme so everyone is on the same page.

**Comment by jcmcneal** [comment]
I have this committed in a branch so I'll hopefully get it out really soon.
