### ISSUE TITLE
WebpackError: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by mathvaleriano** [jcmcneal/react-step-wizard#19]
When I try to build my gatsby application this error occurs and it breaks my build.
I think this can be resolved moving window.addEventListener to componentDidMount.

**Comment by jcmcneal** [comment]
I'm guessing Gatsby is server side rendered? That would explain the error since `window` does not exist in Node.js. I might be able to fix that in the rollup config but if not we may just have to check if `typeof window === undefined` for the event listener. I'll dig into this some more tonight.

**Comment by mathvaleriano** [comment]
I fixed it in my PR #20

**Comment by jcmcneal** [comment]
#24 has been merged and published! Congrats on being the first contributer! 🥇
