### ISSUE TITLE
Does not work with React-Scripts

### ISSUE THREAD

**Issue by leroy0211** [jcmcneal/react-step-wizard#2]
Your component does not work with `react-scripts` because of the css-loader you use: 

`import Styles from '../dist/styles.css';` 

You might have to mention that this does not work with `react-scripts` or you might have to alter the way your styles are imported.

**Comment by jcmcneal** [comment]
Can you post the error message? I believe styles are handled based on your build tool configurations. It looks like `react-scripts` is using webpack.

**Comment by leroy0211** [comment]
Yes, `react-scripts` uses webpack but is not configured to handle css imports by classname. 
All I got on the div's are `undefined` classnames. For example the Step div looks like: 

```
<div class="undefined undefined">
...
</div>
```

**Comment by vsshaposhnikov** [comment]
So, how we could resolve this problem?

**Comment by leroy0211** [comment]
You can eject the react-scripts source, and add the class compiler which handles the classnames. 

Or @jcmcneal could rewrite it to use [styled-components](https://www.styled-components.com/) which is supported by react-scripts.
