### ISSUE TITLE
other step button are clicakble on current active step

### ISSUE THREAD

**Issue by rizkymeiputra** [jcmcneal/react-step-wizard#22]
If the current active step had lower height than the next step, next step button are clickable
see here: https://www.dropbox.com/s/yjh7nu46xzmfn64/simplescreenrecorder-2019-04-04_10.21.11.mp4?dl=0

**Comment by jcmcneal** [comment]
I was confident someone would find this bug. I pushed a fix in #21 so if you update to the newest version that should fix it.

**Comment by rizkymeiputra** [comment]
@jcmcneal 
Great! It's work properly now! Thanks a lot

**Comment by jcmcneal** [comment]
No problem, glad it's working now!
