### ISSUE TITLE
Controlled from parent

### ISSUE THREAD

**Issue by jjalonso** [jcmcneal/react-step-wizard#23]
Hi, its not a bug sorry.

Its possible to set the active children from outside a child?

I have an structure like this.

```
MyContainer
  Buttons
  StepWizard
     Form1
     Form2
```

I want to control the active child from myContainer. Is this possible?

Thanks!

**Comment by jcmcneal** [comment]
This is a great idea and unfortunately there's no clean solution of doing this yet. It does listen for a hash change so you could update the hash with the corresponding hash key but I assume you are looking for a better approach.

Would you prefer to pass down an `activeStep` prop or me provide you with an instance of `StepWizard` with all the props available to steps that you can pass up to the parent?

**Comment by jonathborg** [comment]
Hello, I think the second option is better, StepWizard instance would be great! In future when more options should be added, this will works automatically.
