### ISSUE TITLE
How to use the previous and next function?

### ISSUE THREAD

**Issue by Lilian1331** [jcmcneal/react-step-wizard#26]
Hi all,

I am new to React and have not much knowledge of the component.
May I ask how to use the previous and next function in order to switch through steps?
Below is my current code. Thanks.
```
<StepWizard isLazyMount={true} initialStep={this.currentStep}>
	<div>
		Step 1
	        <p><button onClick={()=>{
			this.currentStep--;
			this.forceUpdate();
		}}>Previous Step</button></p>
		<p><button onClick={()=>{
			this.currentStep++;
			this.forceUpdate();
		}}>Next Step</button></p>
		</div>
			<div>Step 2</div>
			<div>Step 3</div>
			<div>Step 4</div>
		</StepWizard>

```

Thanks for any help.

**Comment by jcmcneal** [comment]
Hi, please see the the sample app I've written as an example. Your steps will need to be components, or functional components, to make use of the next and previous props. Also, you should refrain from using the `forceUpdate` method in React to force a rerender. A component will rerender when either the state or props have changed.

Example code:
https://github.com/jcmcneal/react-step-wizard/blob/master/app/components/wizard.js
