### ISSUE TITLE
isReactComponent is not working with function components

### ISSUE THREAD

**Issue by mathvaleriano** [jcmcneal/react-step-wizard#27]
When we use function components the result of child.type is a function and when we test this.isReactComponent we received function... thats ok. But when execute the app the props have not been passed to child.

**Comment by mathvaleriano** [comment]
Another thing.. when we use memo(Step) the return is something like that:

```
{
  "$$typeof": Symbol(react.memo)
  compare: null
  type: function Step()
}
```

**Comment by mathvaleriano** [comment]
i think it'll be resolved with 

```
isReactComponent = child => typeof child === 'function' || typeof child.type === 'function'
```

**Comment by jcmcneal** [comment]
Should we do what this guy suggested?

https://github.com/jcmcneal/react-step-wizard/pull/21#discussion_r271520314
> Nothing against your fix, just wanted to point out that `Component.prototype.isReactComponent` is provided by React itself. Checkout [this article](https://overreacted.io/how-does-react-tell-a-class-from-a-function/) and [this relevant code](https://github.com/facebook/react/blob/769b1f270e1251d9dbdce0fcbd9e92e502d059b8/packages/react-reconciler/src/ReactFiber.js#L297-L300) from React source.

**Comment by mathvaleriano** [comment]
i never see that before but its awesome :smile:
but i dont know if it works with a returned object from memo() :thinking:

**Comment by mathvaleriano** [comment]
I could not use this prototype with the memo object neither with function components. but I found a very interesting function and it works.

https://reactjs.org/docs/react-api.html#isvalidelement
