### ISSUE TITLE
StepWizard component not responding to `className` and `style` props

### ISSUE THREAD

**Issue by frogThanos** [jcmcneal/react-step-wizard#30]
Hello! 😄 

I'm following the instructions you have regarding moving the Navigation bar to the bottom of the screen but no matter how I try to style to the StepWizard component it just doesn't seem to work. I tried regular css styling by applying a `className`, inline styling with the `style` prop and I've also tried wrapping it in a `styled-component` but nothing works. The StepsWizard component is used in a simple functional component, I've also tried converting it to a class component, that didn't work either. I would really appreciate your help! 😃

**Comment by jcmcneal** [comment]
Sorry mate! I should have caught that a long time ago! I just published `v5.3.0` which now supports `className` 🙂

**Comment by frogThanos** [comment]
Works like a charm!
Thanks! 😄
