### ISSUE TITLE
StepWizard optional initialStep prop

### ISSUE THREAD

**Issue by crobinson42** [jcmcneal/react-step-wizard#4]
Will you accept a PR for passing in the prop `initialStep` to `<StepWizard />` that will cause the step # to render first on initial mount?

This is a useful prop where StepWizard defines a full step flow but some use cases of a StepWizard flow might need to start at step # 'X' ie: skip the first step.

**Comment by crobinson42** [comment]
Or, would you prefer to expose some methods on the StepWizard class so that this logic can be composed in an abstraction, ie:

```
import React, { Component } from 'react'
import {StepWizard, Step} from 'react-step-wizard'

class MyStepWizard extends Component {
  componentDidMount() {
    this.stepWizard.setStep(this.props.initialStep)
  }

  render() {
    return (
      <StepWizard ref={el => this.stepWizard = el}>
        {this.props.children}
      </StepWizard>
    )
  }
}

export default MyStepWizard

```

**Comment by jcmcneal** [comment]
So in your example you should be able to call `goToStep()` and pass the index of the step.

However, I like the idea of adding a `initialStep` prop since that's easier to manage an an `active` prop on the step. If you have a PR I'd be willing to take a look at it.

**Comment by jcmcneal** [comment]
I added the `initialStep` in version 3.0.0. Thanks for the suggestion!
