### ISSUE TITLE
Back Button for Step 1

### ISSUE THREAD

**Issue by thadrinks** [jcmcneal/react-step-wizard#46]
After switching to step 2, the url adds `#step2`. When I hit the back button, it returns back to the original url which doesn't do the transition back to step1 at all. Is there a way to have the back button work on step1 after transitioning to step2?

Thanks!

**Comment by raduchiu** [comment]
I have the same problem.

**Comment by rpresb** [comment]
It's strange as I have the same issue, but I did download the code and it doesn't happen in my forked version. Will dig a bit into this to see what's causing this issue.

**Comment by rpresb** [comment]
I found the reason of failure on my side.

I had this code before

```
        <a
            href='#'
            onClick={() => {
                console.log(`Going back to ${title}`);
                onClick && onClick();
                previousStep();
            }}
        >
            &lt; return to {title}
        </a>
```

But I wasn't preventing the default behaviour of the link.

Fixed code:

```
        <a
            href='#'
            onClick={(e) => {
                e.preventDefault();
                console.log(`Going back to ${title}`);
                onClick && onClick();
                previousStep();
            }}
        >
            &lt; return to {title}
        </a>
```

**Comment by petecroaker** [comment]
this still seems to be occurring...
