### ISSUE TITLE
Lazy Load Steps?

### ISSUE THREAD

**Issue by chobo2** [jcmcneal/react-step-wizard#5]
Hi

Maybe I am doing something wrong but I noticed that all my steps components render at once. Is there away to stop this?

**Comment by sboudouk** [comment]
How many pages your wizard contain ?

**Comment by chobo2** [comment]
@sboudouk 

It will probably have around 5.

**Comment by sboudouk** [comment]
Can you see improvement if you switch to 2 ?

**Comment by chobo2** [comment]
I am running right now "^2.0.0-beta.6", I can try full 2.0. Does 2.0 not run all components at once?

**Comment by sboudouk** [comment]
I'm using latest version and I do not have performance issues. Are your 5 pages heavy/charged ?

**Comment by chobo2** [comment]
@sboudouk 

Yes, some are heavy, but it is not only that some state goes crosses steps(think of review page). With the current setup I have to do if checks as till they fill in the previous step those components will crash.

I think it would be better if they are not active they don't exist.

**Comment by jcmcneal** [comment]
Do you have lifecycle methods like `componentDidUpdate` or `componentWillReceiveProps` in those components?

I'm working on adding an `isActive` prop so you can return null in your render method if `isActive` is set to false. This should alleviate some unnecessary heavy rendering of components not in view.

**Comment by jcmcneal** [comment]
The `isActive` prop has been added to version 3.0.0. Inside your components you can add something like:

```js
render() {
    if (!this.props.isActive) return null

    // the actual content of your component below
}
```

This is as close to "lazy loading" as I'm willing to go for now. I can't guarantee this will resolve your performance issues but do let me know!

**Comment by chobo2** [comment]
@jcmcneal 

Yea that's  pretty much what I ended up doing seeing if  it is currently active. It does help with most of my scenarios but still stuff like "componentDidMount" will still fire off.

Is there a reason why you don't want to implement a feature like this? Are there some drawbacks?

**Comment by jcmcneal** [comment]
True lazy loading would make a network call to import and load each component when requested. It's a great idea and possible, but I'd have to really think that one through to implement it properly.

I could have the parent `StepWizard` component only mount the component that is active. That would only fire `componentDidMount` when `isActive` is true and call `componentWillUnmount` when it exits. That would be a quick fix. Does that work for you?

I'd probably add something like `mountOnActive` prop.

**Comment by jcmcneal** [comment]
@chobo2 

I've added `isLazyMount` to `v4.1.0` which will only mount the active step. Let me know how this works for you.

**Comment by chobo2** [comment]
@jcmcneal 

I have been unable to try it so far. I realize I had such an old version.

I been trying to update it from 

but it breaks my code and I don't know why

Only change I did was go from 2.0.0 to 4.1.0



```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ImporterComponent`.
    in ImporterComponent (created by inject-ImporterComponent-with-uiStores)
    in inject-ImporterComponent-with-uiStores (created by Route)
    in Route (created by MemberAreaComponent)
    in Switch (created by MemberAreaComponent)
    in main (created by MemberAreaComponent)
    in div (created by MemberAreaComponent)
    in div (created by MemberAreaComponent)
    in MemberAreaComponent (created by inject-MemberAreaComponent-with-domainStores-uiStores)
    in inject-MemberAreaComponent-with-domainStores-uiStores (created by Route)
    in Route (created by withRouter(inject-MemberAreaComponent-with-domainStores-uiStores))
    in withRouter(inject-MemberAreaComponent-with-domainStores-uiStores) (created by Route)
    in Route (created by App)
    in Switch (created by App)
    in App (created by inject-App-with-domainStores-uiStores)
    in inject-App-with-domainStores-uiStores (created by Route)
    in Route (created by withRouter(inject-App-with-domainStores-uiStores))
    in withRouter(inject-App-with-domainStores-uiStores)
    in Router
    in Provider
```

  ```
import { StepWizard, Step } from "react-step-wizard";
       <StepWizard>
          <Step>
              <ImportSetupComponent />
          </Step>
          <Step>
              <ImportMappingComponent />
          </Step>
          <Step>
              <ImporterDataValidationComponent />
          </Step>
        </StepWizard> 
```

**Comment by jcmcneal** [comment]
Hey sorry I made some breaking changes since version 2. I decided to get rid of the ‘Step’ component since it was unnecessary and extra bloat. Your components will work without being wrapped in them now. That’s probably the error now.

**Comment by chobo2** [comment]
@jcmcneal 

No worries, that is a good change, I was always wondering about that.

I did that and now it works, however the lazy loading does not seem to work

I tried `isLazyMount={true}` at the StepWizard level and on each step but I still see my component is going through the render method when it should not be.

**Comment by jcmcneal** [comment]
Can you post a code snippet so I can take a look?

**Comment by chobo2** [comment]
@jcmcneal 

```
        <StepWizard isLazyMount>
          <ImportSetupComponent/>
          <ImportMappingComponent  />
        </StepWizard>
```
Also not sure what else is happening but since I upgraded to 4.1 my whole wizard does not work.

I have this component in each that renders the correct button(ie previous, next, submit)

```
 <div className="wizard-nav-controls">
        
        {
          props.currentStep > 1 &&
          <button type="button" className="button is-primary" onClick={this.props.previousStep}>
          Pevious
        </button>
        }
        {props.currentStep > 0 && props.currentStep !== props.totalSteps &&
          <button type="submit" className="button is-primary wizard-next-step">
            Next
          </button>
        }
        
        {this.props.currentStep === this.props.totalSteps &&
          <button  className={this.props.submittingState} onClick={() => this.props.submit()}>
            Submit
          </button>
        }
        
      </div>
```

Now for whatever reason when I click a radio button, I see 2 next buttons.

Also when I do finally hit next the wizard renders the next step under the current step. So it is not hiding it.

Maybe everything is related.

**Comment by chobo2** [comment]
Ok, I think it might be working. It is really weird. I am using: https://www.npmjs.com/package/npm-check-updates

and I used it to update to version 4.1 and in my package.json it said it updated but in my package-lock.json it still had stuff about 2.0.0 so I think it was not using the correct version.

**Comment by jcmcneal** [comment]
Yeah, I've been cleaning up code and created some breaking changes, hence the recent major version bumps.

Your syntax looks correct. So you're staying the lazy loading is working for you now?

**Comment by chobo2** [comment]
@jcmcneal 

I got to do more investigation but I think so, I don't think that plugin that I am using to update my packages updated everything fullly. It changed the version in package.json but from what it looked like to me it was still on 2.0 maybe because the package-lock was not updated.

**Comment by jcmcneal** [comment]
It helps to delete the node_modules folder, update the version in package.json, and reinstall. Or you can force a specific version like `yarn add react-step-wizard@4.1.0`.

Anyway, if that works let me know and I'll close out this issue.

**Comment by chobo2** [comment]
@jcmcneal 

Hey it does seem to be working but does your new version work with IE 11. I just noticed that my site no longer works in IE 11.

When I delete react-step-wizard and remove the imports, it works again in IE 11.

**Comment by jcmcneal** [comment]
You're right, something I changed broke IE 11 so when I get a chance I'll dig into it.

**Comment by chobo2** [comment]
@jcmcneal 

Not surprised, happens to me quite a lot, I right a feature for work then few days go by and I am like "hmm did I try it in IE 11".

Another question about the lazy loading option. Does it destroy/unmount the previous step?

**Comment by jcmcneal** [comment]
Yes it does unmount all the other steps. If it stays mounted then `componentDidUpdate` would fire on them anytime their props change, which sounded like you didn't want.

**Comment by chobo2** [comment]
@jcmcneal 

No worries, I will code my components accordingly (I guess on mounting, I will have to check if any data was filled in and then repopulate everything), but I was actually thinking of the constructor and componentWillMount, I have not had really had a need to compoentDidUpdate so did not even cross my mind. 

I was more thinking about it in terms of Entityframework lazy loading once it is loaded, it is in memory for good.

For me the bigger concern is the IE 11 thing as I sadly must support it.

**Comment by jcmcneal** [comment]
I haven't heard of Entityframework so I'll have to look into that.

I believe the IE bug is an issue with the babel configuration. I've been following their documentation trying different things, testing polyfills, etc, and can't get it to work yet. I don't see the same error you do so it's hard to pinpoint. I'll keep working on it though.

**Comment by chobo2** [comment]
@jcmcneal 

Entityframework is an ORM for C#. Like most ORMs they lazy load into memory. 

Let me know if I can be any assistance.  What I see is 

"SCRIPT1002: Syntax error, File: main.js, Line: 72552, Column: 9610"

**Comment by jcmcneal** [comment]
@chobo2 Hey I finally figured out the IE issue. It was a bad babel configuration. It's in `v4.1.2`

If it helps, this meta tag will tell IE to run the highest standards up to IE 11:
```<meta http-equiv="x-ua-compatible" content="IE=edge">```

Let me know if that works for ya.

**Comment by jcmcneal** [comment]
Definitely update to `v4.1.2`. You only want to use that meta tag if you need to support IE lower than IE11.

**Comment by chobo2** [comment]
@jcmcneal 

Ok, I will try v4.1.2, IE 11 is the lowest I am willing to support. The meta tag seems to bit confusing as it has "edge" in it, thought maybe it tries to put it up to "edge".

**Comment by jcmcneal** [comment]
That's the lowest I support as well. It's true, `edge` is ambiguous but Microsoft beats to their own drum.

Closing this issue. If there are anymore IE issues please open a new issue.
