### ISSUE TITLE
Wizard throws error when using conditional steps

### ISSUE THREAD

**Issue by wallawe** [jcmcneal/react-step-wizard#55]
I have a "creation flow" that requires a payment form if the user hasn't got a credit card attached to their account. So this step is conditional, and looks like this: 
![image](https://user-images.githubusercontent.com/1158544/71675538-f1c15d80-2d4b-11ea-8544-c9b0bb3406ac.png)

This throws an error if they do have a card source attached since that step is null. 

Here's the solution I used to fix it in my forked version:

![image](https://user-images.githubusercontent.com/1158544/71675643-377e2600-2d4c-11ea-9a1c-2421994af0ca.png)

![image](https://user-images.githubusercontent.com/1158544/71675659-41078e00-2d4c-11ea-91f2-09cfc29c1db9.png)

If you'd like me to submit a PR, I'd be glad to.

**Comment by juunp** [comment]
I created the PR with your code and added tests, if it is a problem, let me known.

**Comment by skhamoud** [comment]
Any update on this issue and PR ? It's a pretty commmon issue I think and it needs handling

**Comment by jcmcneal** [comment]
This has been added in [v5.3.1](https://github.com/jcmcneal/react-step-wizard/releases/tag/5.3.1). Thanks for the help!
