### ISSUE TITLE
Error when loading stepwizard

### ISSUE THREAD

**Issue by ServicedeskZenabis** [jcmcneal/react-step-wizard#63]
Im getting the following error when trying to use the stepwizard

TypeError: o.props.children.filter is not a function
a.getSteps
node_modules/react-step-wizard/dist/react-step-wizard.min.js:1

**Comment by ServicedeskZenabis** [comment]
Just changes the version from 5.3.2 to 5.3.0 and now its working.

**Comment by resolritter** [comment]
> Just changed the version from 5.3.2 to 5.3.0 and now its working.

according to this, I'll be now closing this issue
