### ISSUE TITLE
Failure if there is only one child of the stepwizard

### ISSUE THREAD

**Issue by BFUculsion** [jcmcneal/react-step-wizard#65]
If you have only one child component in the step wizard, you get this error
×
TypeError: o.props.children.filter is not a function
a.getSteps
node_modules/react-step-wizard/dist/react-step-wizard.min.js:1

**Comment by nmoinvaz** [comment]
I had this same error and it took me quite some time to figure out what was happening. For some reason I thought it was missing Array.filter polyfill.

https://stackoverflow.com/questions/32672966/react-props-children-is-not-array

**Comment by nmoinvaz** [comment]
Duplicates #62.

**Comment by nmoinvaz** [comment]
Duplicates #63.
