### ISSUE TITLE
Installing package from git repository doesn't work

### ISSUE THREAD

**Issue by nmoinvaz** [jcmcneal/react-step-wizard#66]
When trying to install the package directly from github it does not work:
```
yarn add https://github.com/jcmcneal/react-step-wizard
```
And results in:
```
Module not found: Can't resolve 'react-step-wizard' in 'C:\Source\create-react-app\src'
```
This is due to invalid _main_ property in package.json_ of `dist/react-step-wizard.min.js` which should be `src/index.js`.

I think that the npm package should not be minfiied _dist_. It prevents projects from overriding babel configuration with project-wide _babel.config.json_. Thank you.

**Comment by jcmcneal** [comment]
NPM modules are generally packaged and minified ready for production. May I ask why you prefer to bundle it in your parent app? It just doesn't seem like a good practice for any NPM module.

The main has to be set to `dist/react-step-wizard.min.js` in order for it to work properly as a module, thus I wouldn't be able to support both dist and src.

An alternative is to fork this repo and host it on your own github account but again I think it's ideal to install from npm repository.

**Comment by nmoinvaz** [comment]
I had my own fork and that is why I wanted to install the package from my own git repository.
