### ISSUE TITLE
transfer props from one step to another on goTostep()

### ISSUE THREAD

**Issue by morelgarisi** [jcmcneal/react-step-wizard#69]
is it possible  to transfer data from one step to the other?

**Comment by resolritter** [comment]
It's possible to keep the state between different steps by synchronizing them in a parent component. For instance, [formik-wizard](https://github.com/zaguiini/formik-wizard/) does this by sharing the steps' state in Formik's context.

Currently its implementation is based on `react-albus`, but the creator of that library has announced [here](https://github.com/zaguiini/formik-wizard/pull/32#issuecomment-654162510) that he's working on a new version which could support `react-step-wizard`.

**Comment by jcmcneal** [comment]
I agree with @resolritter, you'll want to manage state outside of the step wizard. I have a basic example of that in this repo but there are a lot of solutions like Redux or React Context that you can use to accomplish the same thing.
