### ISSUE TITLE
Vertical transitions instead of horizontal

### ISSUE THREAD

**Issue by krichdev** [jcmcneal/react-step-wizard#74]
Is there a way to use vertical transitions instead of the horizontal ones?

**Comment by jcmcneal** [comment]
Yep. The [transitions](https://github.com/jcmcneal/react-step-wizard#transitions) are all based on CSS animations. You'll have to create your own animations and pass those classes in like this:

```
const transitions = {
  enterRight: 'your custom css transition classes',
  enterLeft : 'your custom css transition classes',
  exitRight : 'your custom css transition classes',
  exitLeft  : 'your custom css transition classes'
}
<StepWizard transitions={transitions}>...</StepWizard>
```

**Comment by BFMarks** [comment]
This does not seem to work anymore
