### ISSUE TITLE
Step change button not working

### ISSUE THREAD

**Issue by andresdellachiesa** [jcmcneal/react-step-wizard#75]
Hello there!
I have the following code:

```
                        <StepWizard transitions={noTransitions} isHashEnabled>
                            <fieldset>
                                <h5>fsdfdsfsdf</h5>
                                <button className='btn btn-primary btn-block' onClick={nextStep}>Continue</button>
                            </fieldset>
                            <fieldset isActive>
                                <h5>dsggdfg</h5>
                                <button className='btn btn-default btn-block' onClick={previousStep}>Go Back</button>
                            </fieldset>
                        </StepWizard>
```
Nevertheless, when I click on Continue button, nothing changes. The page reloads, but nothing changes.
Any ideas?

Thanks in advance.

**Comment by andresdellachiesa** [comment]
I realise that none of the props functionalities are coming with props. Any ideas on this?

**Comment by resolritter** [comment]
The children have to be functions or React Components for getting access to the props

https://github.com/jcmcneal/react-step-wizard/blob/6ee7978ccc08021c7e2ca54d9d77a6de3b992117/src/index.js#L189-L190

See this code sandbox https://codesandbox.io/s/pensive-spence-uephm?file=/src/App.js

i.e. you could change your example to this

```javascript
                        <StepWizard>
                           <Step1 />
                           <Step2 />
                        </StepWizard>
```
