### ISSUE TITLE
Feature request: navigation

### ISSUE THREAD

**Issue by arjendejong12** [jcmcneal/react-step-wizard#8]
I'd like to request a new feature: navigation. Something like this: https://semantic-ui.com/elements/step.html. For that we need to know which steps are finished. Is it possible to integrate this?

**Comment by jcmcneal** [comment]
There you go @arjendejong12! The `nav` prop has been added in version `4.4.0`. Check out my example nav for an idea of how you can build your own. Good luck! :)

**Comment by arjendejong12** [comment]
Awesome work! Would you be able to add a prop which marks a nav step complete, so I would be able to have a different style for the nav steps that are completed?

**Comment by jcmcneal** [comment]
You would have to manage which steps are completed outside the step wizard since you create the steps and validation. You could then pass that information as a prop to your nav component to handle the logic.
