### ISSUE TITLE
Nav at bottom - <StepWizard style={{ flexDirection: "column-reverse" }} nav={<Nav1 />} > does not works

### ISSUE THREAD

**Issue by muriloneo** [jcmcneal/react-step-wizard#80]
How can I put Nav at bottom? - 

`<StepWizard style={{ flexDirection: "column-reverse" }} nav={<Nav1 />} >` does **not** work.

At the demo it's not all clear how it does.
[https://github.com/jcmcneal/react-step-wizard/tree/76723d6b8105a720f1968fa0c60128c780105337/app]

**Comment by jcmcneal** [comment]
The parent component does not accept a `style` prop. You must define a css class and pass it to the `className` prop and it should work for you!
