### ISSUE TITLE
On 'Enter' the wizard gets to the next step

### ISSUE THREAD

**Issue by iamalextodoran** [jcmcneal/react-step-wizard#81]
When pressing the enter key the wizard gets to the next step and skips all my validations. I tried preventing the default, but didn't work.

**Comment by jcmcneal** [comment]
If you haven't figured it out already, can you post a snippet of your code?

**Comment by iamalextodoran** [comment]
I've disabled the action on key press with useEffect, so far it's fine and seems to work well.

```
useEffect(() => {
    const handleUserKeyPress = event => {
      if (event.key === 'Enter') {
        event.preventDefault();
      }
    };

    window.addEventListener('keydown', handleUserKeyPress);'

    return () => {
      window.removeEventListener('keydown', handleUserKeyPress);
    };
}, []);
```
