### ISSUE TITLE
Is there a straightforward way to deploy the wizard as a modal?

### ISSUE THREAD

**Issue by slimandslam** [jcmcneal/react-step-wizard#92]
I guess this is a feature request. I'm wondering if there is a straightforward way to deploy a wizard as a modal.

**Comment by masudhossain** [comment]
Just create a modal component and add it there.

**Comment by bundit** [comment]
As @masudhossain said you can just wrap it with a modal component. EX:

```
<Modal isOpen={xxx}>
     <ReactStepWizard>
     .....
     </ReactStepWizard>
</Modal>
```
